### ISSUE TITLE
[Error] array must be initialized with a brace-enclosed initializer

### ISSUE THREAD

**Issue by Nike-rgb** [dou-d/128#3]
In line 17 of the logic.h file.

**Comment by dipudl** [comment]
Some compiler allow it while others don't, but conventionally two-dimensional array should be initialized with double curly braces.
So, '{0}' on line 17 has been changed to '{{0}}'. Please check if it works on your side.

Reference: https://stackoverflow.com/questions/4329324/c-error-array-must-be-initialized-with-a-brace-enclosed-initializer

**Comment by Nike-rgb** [comment]
Yay it worked!!!
